config/routes.rb
Rails.application.routes.draw do
  devise_for :users#, only: []  

   resources :videos do#, only: [:index, :show] do
    member do
      put "upvote", to: "videos#upvote"
      put "downvote", to: "videos#downvote"
    end
  end
  root 'videos#index', as: :root
  get 'videomasterindex/mostupvoted'
  get 'videomasterindex/alphabetical'
  get 'videomasterindex/mostrecent'
  get 'videomasterindex/getpaid'
  get 'videomasterindex/contactus'
  get 'videomasterindex/search'

  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beenheretracker.rb
class Beenheretracker < ApplicationRecord
end

app/models/ipaddresstracker.rb
class Ipaddresstracker < ActiveRecord::Base
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/video.rb
class Video < ActiveRecord::Base
    mount_uploader :file, VideoUploader
    acts_as_votable
    
    # def self.search(search)
    #     where("title LIKE ?", "%#{search}%") 
    # end
    def self.search(search, id)
        if search
            where(['title LIKE ?', "%#{search}%"])
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/videomasterindex_controller.rb
class VideomasterindexController < ApplicationController
    
    def mostupvoted
        @videos = Video.all.order(:cached_votes_up=> :desc).paginate(:page => params[:page], :per_page => 6)
    end
    
    def alphabetical
        @videos = Video.order(title: :asc).paginate(:page => params[:page], :per_page => 6)
        @ip = request.remote_ip
        @beenhere = Beenheretracker.find_by(ipaddress: @ip)
    end
    
    def mostrecent
        @videos = Video.order(created_at: :desc).paginate(:page => params[:page], :per_page => 6)
    end
    
    def randomized
        @videos = Video.all.shuffle.paginate(:page => params[:page], :per_page => 6)
    end
    
    def getpaid
        Beenheretracker.delete_all
    end
    
    def contactus
        
    end
    
    def search
        # if params[:search]
        #     @posts = Video.search(params[:search])
        # else
            @tempposts = Video.order(title: :asc)
            @posts = []
            @tempposts.each do |x|
                boo = false
                @posts.each do |y|
                    if x.title == y.title
                        boo = true
                    end
                end
                if boo == false
                    @posts.push(x)        
                end
            end
        # end
    end
    
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]



  def upvote
    @video = Video.find(params[:id])
    @ip = request.remote_ip
    @was_it_upvoted = Ipaddresstracker.find_by(ipaddress: @ip, videoid: @video.id)
    if @was_it_upvoted
      @video.downvote_by User.first
      @was_it_upvoted.delete
    else
      Ipaddresstracker.create(:ipaddress => @ip, :videoid => @video.id)
      @video.vote_by voter: User.first, :duplicate => true
    end
  end

  def downvote
    @video = Video.find(params[:id])
    @video.downvote_by User.first
    redirect_to :back
  end
  
  # GET /videos
  # GET /videos.json
  def index
    # @videos = Video.search(params[:search], params[:id]).order(:cached_votes_total=> :desc)
    if params[:search]
      @videos = Video.where('title LIKE ?', "%#{params[:search]}%")
    else
      @ip = request.remote_ip
      Beenheretracker.create(:ipaddress => @ip)
      @beenhere = Beenheretracker.find_by(ipaddress: @ip)
      @videos = Video.order(title: :asc).paginate(:page => params[:page], :per_page => 6)
      if @videos 
      
      else
        @videos = Video.all
      end
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    # puts params[:id]
    @boolean = params[:boolean]
    title = Video.find(params[:id]).title
    @videos = []
    Video.all.each do |x|
      if x.title == title
        @videos.push(x)
      end
    end
    @videos = @videos.shuffle
  end

  # GET /videos/new
  def new
    @video = Video.new
    @videos = Video.order(title: :asc).paginate(:page => params[:page], :per_page => 6)
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  
  def create
    @video = Video.new(video_params)
    
    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :file, :contributor, :email, :phone, :search)
    end
end

# have pop up messages based on IP address (vote without an account, make an account to save videos, mark seen ones..)

# what video file types can i actually upload

# how to upvote without the page reloading

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videomasterindex_helper.rb
module VideomasterindexHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/_navbar.html.erb
<nav class="fh5co-nav" role="navigation">
  <div class="container">
    <div class="fh5co-top-logo">
      <div id="fh5co-logo"><a href="<%= home_path %>">Day In The Life Of</a></div>
    </div>
    <div class="fh5co-top-menu menu-1 text-center">
      <ul>
        <li><a href="<%= videomasterindex_search_path %>">Search</a></li>
        <li><a href="<%= videomasterindex_getpaid_path %>">Get Paid</a></li>
        <li><a href="<%= videomasterindex_contactus_path %>">Contact Me</a></li>
        <li><a href="<%= new_video_path %>">Videos New</a></li>
      </ul>
    </div>
  </div>
</nav>
<br />
<br />
<br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workspace</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>


    <!-- <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet" id="bootstrap-css"> -->
    <!-- <script src="//code.jquery.com/jquery-1.11.1.min.js"></script> -->
  </head>
  <body>
    <nav class="navbar navbar-default" style="margin-top: 30px;">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="<%=root_path%>">Day In The Life Of</a>
        </div>
        <ul class="nav navbar-nav">
          <li><a href="/videomasterindex/search">Search</a></li>
          <li>
            <% if @beenhere %>
              <a href='/videomasterindex/getpaid' data-step='1' data-intro='Learn How to Get Paid By Us!' data-position="right"> Get Paid </a> 
            <% else %>
              <a href='/videomasterindex/getpaid'> Get Paid </a> 
            <% end %>
          </li>
          <li><a href="/videomasterindex/contactus">Contact Me</a></li>
          <li><a href="/videos/new">Videos New</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><a href="/users/sign_up">Sign Up</a></li>
            <li><a href="/users/sign_in">Sign In</a></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <% if notice %>
        <div class="alert alert-success alert-dismissible">
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <%= notice %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/videomasterindex/_index.html.erb
<div class="row">
  <% @videos.each do |x| %>
    <div class="col-md-4">  
      <video controls width="310" height="230" src="<%= x.file %>"></video>
      <div class="btn-group row">
        <div class="col-md-12">
          <%= link_to upvote_video_path(x), method: :put, remote: :true, id: "like-count", class: "btn btn-default btn-sm" do %>
            <span class="glyphicon glyphicon-chevron-up"></span>Upvote
            <div> <%= x.get_upvotes.size.to_s + " / " + x.title %> </div>
          <% end %>
    
          <%#= link_to dislike_video_path(x), method: :put, remote: :true, id: "like-count", class: "btn btn-default btn-sm" do %>
            <!-- <span class="glyphicon glyphicon-chevron-down"></span>Downvote -->
            <%#= x.get_downvotes.size %>
          <%# end %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <br>
          <table class="table table-bordered" style="width:310px;">
            <tbody>
              <tr>
                <td><strong>Contributor:</strong></td>
                <td><%= x.contributor %></td>
              </tr>
              <tr>
                <td><strong>Email:</strong></td>
                <td><%= x.email %></td>
              </tr>
              <tr>
                <td><strong>Phone:</strong></td>
                <td><%= x.phone %></td>
              </tr>
              <tr>
                <td></td>
                <td><%= link_to 'Destroy', x, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= will_paginate @videos %>

<br><br>

app/views/videomasterindex/alphabetical.html.erb
<div class="row mb-20">
  <div class="col-md-3">
    <div class="displayoption">
      <%save_options = [['Most Upvoted','videomasterindex/mostupvoted'],['Most Recent','videomasterindex/mostrecent'],['Alphabetical','videomasterindex/alphabetical']]%>
      <%= select_tag "store-selects", options_for_select(save_options),:onchange => "self.location='/'+this.options[this.selectedIndex].value", class: "your_class form-control" %>
    </div>
  </div>
</div>

<%= render 'index' %>

app/views/videomasterindex/contactus.html.erb
<div class="page-header page-header-bordered page-header-tabs">
  <h1 class="page-title">
  	Contact Us
  </h1>
</div>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

app/views/videomasterindex/getpaid.html.erb
<div class="page-header page-header-bordered page-header-tabs">
  <h1 class="page-title">
  	Get Paid
  </h1>
</div>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

app/views/videomasterindex/index.hmtl.erb
<h1>Index Page</h1>

<%= form_tag videos_path, :method => 'get'  do %>
   <%= text_field_tag :search, params[:search]%>
   <%= submit_tag "Search", :name => nil  %>
 <% end %>

<hr />
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 <tr>
  <td><hr></td>
  <td><hr></td>
</tr>
  <% @posts.each do |post| %>

    <tr>
      <td><%= post.title %></td>
    </tr>
    <tr>
      <td><hr></td>
      <td><hr></td>
    </tr>
  <% end %>
</table>

app/views/videomasterindex/like.js.haml
$('#like-count').html("#{@article.get_upvotes.size}");

app/views/videomasterindex/mostrecent.html.erb
<div class="row mb-20">
  <div class="col-md-3">
    <div class="displayoption">
      <%save_options = [['Most Upvoted','videomasterindex/mostupvoted'],['Most Recent','videomasterindex/mostrecent'],['Alphabetical','videomasterindex/alphabetical']]%>
      <%= select_tag "store-selects", options_for_select(save_options),:onchange => "self.location='/'+this.options[this.selectedIndex].value", class: "your_class form-control" %>
    </div>
  </div>
</div>

<%= render 'index' %>

app/views/videomasterindex/mostupvoted.html.erb
<div class="row mb-20">
  <div class="col-md-3">
		<div class="displayoption">
			<%save_options = [['Most Upvoted','videomasterindex/mostupvoted'],['Most Recent','videomasterindex/mostrecent'],['Alphabetical','videomasterindex/alphabetical']]%>
			<%= select_tag "store-selects", options_for_select(save_options),:onchange => "self.location='/'+this.options[this.selectedIndex].value", class: "your_class form-control" %>
		</div>
	</div>
</div>

<%= render 'index' %>

app/views/videomasterindex/randomized.html.erb
<div class="displayoption"><%save_options = [['Randomized','videomasterindex/randomized'],['Most Recent','videomasterindex/mostrecent'],['Most Upvoted','videomasterindex/mostupvoted'],['Alphabetical','videomasterindex/alphabetical']]%>
<%= select_tag "store-selects", options_for_select(save_options),:onchange => "self.location='/'+this.options[this.selectedIndex].value", class: "your_class" %>
</div>

<div class="container">
<% @videos.each do |x| %>
<p> <div class="child">  
  <video controls width="310" height="230" src="<%= x.file %>"></video>
    <p> <%= x.title %> </p>

          <div class="btn-group">
            <%= link_to like_video_path(x), method: :put, remote: :true, id: "like-count", class: "btn btn-default btn-sm" do %>

            <span class="glyphicon glyphicon-chevron-up"></span>
            Upvote
            <div> <%= x.get_upvotes.size %> </div>
      <% end %>
          <%= link_to dislike_video_path(x), method: :put, remote: :true, id: "like-count", class: "btn btn-default btn-sm" do %>
          <span class="glyphicon glyphicon-chevron-down"></span>
          Downvote
          <%= x.get_downvotes.size %>
          <% end %>
          <div>
            <br><br>
            <% if user_signed_in? %>
              <p> Contributor: <%= x.contributor %> </p>
              <p> Email: <%= x.email %> </p>
              <p> Phone: <%= x.phone %> </p>
              <p> <%= link_to 'Destroy', x, method: :delete, data: { confirm: 'Are you sure?' } %> </p>
            <% end %>
          </div>
          </div>
          

</div> </p>
<% end %>
</div>

<%= will_paginate @videos %>

app/views/videomasterindex/search.html.erb
<!-- <h1 class="searchcolumn">Search Function</h1> -->
<!-- <br> -->
<div class="searchcolumn">
  <%= form_tag videos_path, :method => 'get', class: "form-inline" do %>
    <div class="form-group">
      <%= text_field_tag :search, params[:search], class: "form-control" %>
    </div>
    <%= submit_tag "Search", :name => nil, class: "btn btn-primary" %>
 <% end %>
</div>
<hr/>

<div class="searchcolumn">
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= link_to post.title, video_path(post) %></td>
          <!--<td> <= post %> </td>-->
          <!--<td> <= button_to "Some Button", { :controller => "videomasterindex", :action => "somebutton"} %> </td>-->
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/videomasterindex/somebutton.html.erb
<h1>Some Button</h1>

app/views/videos/_book.html.erb
<p> Title: <%= book.get_upvotes.size %> </p>

app/views/videos/_form.html.erb
<%= form_for @video do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: "control-label col-sm-2" %>
    <div class="col-sm-6">
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="clear"></div>
  </div>

  <div class="form-group">
    <%= f.label :contributor, class: "control-label col-sm-2" %>
    <div class="col-sm-6">
      <%= f.text_field :contributor, class: "form-control" %>
    </div>
    <div class="clear"></div>
  </div>

  <div class="form-group">
    <%= f.label :email, class: "control-label col-sm-2" %>
    <div class="col-sm-6">
      <%= f.text_field :email, class: "form-control" %>
    </div>
    <div class="clear"></div>
  </div>

  <div class="form-group">
    <%= f.label :phone, class: "control-label col-sm-2" %>
    <div class="col-sm-6">
      <%= f.text_field :phone, class: "form-control" %>
    </div>
    <div class="clear"></div>
  </div>

  <div class="form-group">
    <%= f.label :file, class: "control-label col-sm-2" %>
    <div class="col-sm-6">
      <%= f.file_field :file, class: "form-control" %>
    </div>
    <div class="clear"></div>
  </div>

  <div class="form-group">
    <div class="col-sm-2"></div>
    <div class="col-sm-6">
      <%= f.submit class: "btn btn-primary" %>
    </div>
    <div class="clear"></div>
  </div>
  
<% end %>

app/views/videos/_index.html.erb
<div class="row mb-20">
  <div class="col-md-3">
    <div class="displayoption">
      <% save_options = [['Alphabetical','videomasterindex/alphabetical'],['Most Upvoted','videomasterindex/mostupvoted'],['Most Recent','videomasterindex/mostrecent']] %>
      <%= select_tag "store-selects", options_for_select(save_options),:onchange => "self.location='/'+this.options[this.selectedIndex].value", class: "your_class form-control" %>
    </div>
  </div>
</div>

<% bool = true %>
<div class="row">
  <% @videos.each do |x| %>
    <div class="col-md-4">  
      <video controls width="310" height="230" src="<%= x.file %>"></video>
      <div class="btn-group upvotingthis row">
        <div class="col-md-12">
          <% if bool && @beenhere %>
            <div data-step='2' data-intro="Upvote without an Account!" data-position="top">
              <%= link_to upvote_video_path(x), method: :put, remote: :true, class: "btn btn-default btn-sm" do %>
                <span class="glyphicon glyphicon-chevron-up"></span>Upvote
                <div class="random-book" id= "<%= dom_id(Video.find(x.id)) %>" > <%= x.get_upvotes.size.to_s + " / " + x.title %></div>
              <% end %>
            </div>
            <% Beenheretracker.create(:ipaddress => @ip) %>
          <% else %>
            <%= link_to upvote_video_path(x), method: :put, remote: true, id: "like-count", class: "btn btn-default btn-sm" do %>
              <span class="glyphicon glyphicon-chevron-up"></span>Upvote
              <div class="random-book" id= "<%= dom_id(Video.find(x.id)) %>" > <%= x.get_upvotes.size.to_s + " / " + x.title %></div>
            <% end %>
          <% end %>
        </div>
      </div>
      <% bool = false %>
      <% if user_signed_in? %>
        <div class="row">
          <div class="col-md-12">
            <br>
            <table class="table table-bordered" style="width:310px;">
              <tbody>
                <tr>
                  <td><strong>Contributor:</strong></td>
                  <td><%= x.contributor %></td>
                </tr>
                <tr>
                  <td><strong>Email:</strong></td>
                  <td><%= x.email %></td>
                </tr>
                <tr>
                  <td><strong>Phone:</strong></td>
                  <td><%= x.phone %></td>
                </tr>
                <tr>
                  <td></td>
                  <td><%= link_to 'Destroy', x, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<script>
// self executing function here
(function() {
  introJs().start();
})();
</script>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<!-- <= form_tag videos_path, :method => 'get'  do %>
   <= text_field_tag :search, params[:search]%>
   <= submit_tag "Search", :name => nil  %>
 < end %> -->

<%= render 'index' %>

app/views/videos/indexsave.html.erb
<h1>Listing Videos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>File</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
        <td><%= video.file %></td>
        <td> <video controls width="320" height="240" src="<%= video.file %>"></video>
        
          <div class="btn-group">
            <!--<a class="btn btn-default btn-sm" href="<   = link.url %>">Visit Link</a>-->
            <%= link_to like_video_path(video), method: :put, class: "btn btn-default btn-sm" do %>
            <span class="glyphicon glyphicon-chevron-up"></span>
          Upvote
          <%= video.get_upvotes.size %>
          <% end %>
          <%= link_to dislike_video_path(video), method: :put, class: "btn btn-default btn-sm" do %>
          <span class="glyphicon glyphicon-chevron-down"></span>
          Downvote
          <%= video.get_downvotes.size %>
          <% end %>
          </div>
        
        
        
        
        </td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<div class="page-header page-header-bordered page-header-tabs">
  <h1 class="page-title">
  	New Video
		<small class="pull-right"><%= link_to 'Back', videos_path %></small>
  </h1>
</div>
<%= render 'form' %>



<!-- steps are to create a PG dump file, upload it to amazons3 then use command: heroku pg:backups restore 'https://s3.amazonaws.com/me/items/3H0q/mydb.dump' DATABASE_URL to import your database -->


<!-- 
 heroku pg:backups:restore https://s3.amazonaws.com/s3-us-west-1.amazonaws.com/dayinthelifeofbucket/mydb.dump?AWSAccessKeyId=AKIAJP42TRMYFUMB764A&Expires=1555401128&Signature=e%2B9So5G1SvIqqpWXZzquC5qXEBA%3D postgres://tjmiduudpsopca:449758076e7eaf8f4995ad82c8277131c3398c41a99e648f6e81c55d585ef05a@ec2-50-17-227-28.compute-1.amazonaws.com:5432/dqcr0or9hahbs -->

app/views/videos/show.html.erb
<%= render 'index' %>

app/views/videos/upvote.js.erb
$('#<%=dom_id(Video.find(@video.id))%>').html("<%= j (render partial: 'book', locals: { book: @video }) %>")
console.log('#<%=dom_id(Video.find(@video.id))%>')
console.log(Rails.$('.random-book')[0])
// Rails.$('.random-book')[1].innerHTML = ("<%= j (render partial: 'book', locals: { book: @video }) %>")